services:
  backend:
    container_name: backend_service
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MQTT_CONNECTION_URL=${MQTT_BACKEND_CONNECTION_URL}
      - MONGO_URI=${MONGO_URI}
      - MQTT_TOPIC=${MQTT_TOPIC}
      - MQTT_COMMAND_TOPIC=${MQTT_COMMAND_TOPIC}
    depends_on:
      mqtt:
        condition: service_healthy
      database:
        condition: service_healthy
    ports:
      - 3000:3000
    networks:
      - local_net

  pubsub1:
    container_name: pubsub1
    image: 2csolutionhub/pubsub-node:0.0.1
    environment:
      - MQTT_CONNECTION_URL=${PUBSUB_MQTT_CONNECTION_URL}
      - APP_PORT=${PUBSUB_APP_PORT}
      - APP_LOG_LEVEL=${PUBSUB_APP_LOG_LEVEL}
    depends_on:
      mqtt:
        condition: service_healthy
      database:
        condition: service_healthy
    networks:
      - local_net

  pubsub2:
    container_name: pubsub2
    image: 2csolutionhub/pubsub-node:0.0.1
    environment:
      - MQTT_CONNECTION_URL=${PUBSUB_MQTT_CONNECTION_URL}
      - APP_PORT=${PUBSUB_APP_PORT}
      - APP_LOG_LEVEL=${PUBSUB_APP_LOG_LEVEL}
    depends_on:
      mqtt:
        condition: service_healthy
      database:
        condition: service_healthy
    networks:
      - local_net

  mqtt:
    container_name: mqtt
    build:
      context: ./mqtt_config
      dockerfile: Dockerfile
    ports:
      - 1883:1883
      - 5672:5672
      - 15672:15672
    networks:
      - local_net
    volumes:
      - ./mqtt_config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.config
      - ./mqtt_config/definitions.json:/opt/definitions.json
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  database:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - local_net
    volumes:
      - db_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping")' | mongo
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  local_net:
    driver: bridge

volumes:
  db_data:
    driver: local

